### ISSUE TITLE
WalletGreen doesn't check balance before attempting to generation transactions.

### ISSUE THREAD

**Issue by arbourp** [CalexCore/AmityCoin-DO-NOT-USE#15]
If you try to send a large amount(haven't tested with any different sizes yet), i.e. 1000 AMIT from your wallet and that amount isn't in your available balance the wallet locks up waiting for the transactions to confirm.

Below is what it looks like:

Created 1 fusion transaction!
Created 2 fusion transactions!
Created 3 fusion transactions!
Created 4 fusion transactions!
Created 5 fusion transactions!
Created 6 fusion transactions!
Created 7 fusion transactions!
Created 8 fusion transactions!
Created 9 fusion transactions!
Created 10 fusion transactions!
Created 11 fusion transactions!
Created 12 fusion transactions!
Created 13 fusion transactions!
Created 14 fusion transactions!
Created 15 fusion transactions!
Created 16 fusion transactions!
16 fusion transactions have been sent, waiting for balance to return and unlock

Balance is still locked, 16 fusion transactions still to be confirmed.
Will try again in 15 seconds...
Balance is still locked, 16 fusion transactions still to be confirmed.
Will try again in 15 seconds...
Balance is still locked, 16 fusion transactions still to be confirmed.
Will try again in 15 seconds...
Balance is still locked, 16 fusion transactions still to be confirmed.
Will try again in 15 seconds...
Balance is still locked, 16 fusion transactions still to be confirmed.
Will try again in 15 seconds...

Seems a known issue with the SimpleWallet
https://github.com/turtlecoin/turtlecoin/issues/114

**Comment by michael-herwig** [comment]
Hello @arbourp and thanks for your submission and detailed description. I will try to reproduce it and have a look whether I can fix it shortly.

**Comment by arbourp** [comment]
I don't think it is a huge deal and I'm not sure exactly how it happened.
I tried to send 1500 AMIT and it just got hung up there.  It seems that my balance was locked. I didn't even think to check(assumed that the tools would stop me from sending more than I have).

I'm thinking it might be as simple as checking the available balance prior to initiating the send..
Or could be incredibly complicated. what do I know? Not much they say.. not much.

**Comment by CRTNFACE** [comment]
Is the balance unlocked in your wallet? We’ll be doing the TRTL walletgreen rewrite which might help solve this issue. It could be a case of PEBCAK but the rewrite was on the horizon anyway. We’ve had other members being able to send 4K at once so I’m not sure what’s gone on here, anyway we will help resolve this issue

**Comment by arbourp** [comment]
I haven't been able to reproduce yet, I need to move some balance over to my second wallet so i can test and see what happens when I do that. The total balance was definitely enough, and the wallet certainly screams loud enough when you try and move what you don't have.
I suspect there may be a problem in things that are not unlocked at the time that the wallet tries to move them.

I'll get back later once I have some more time to test this out.

**Comment by arbourp** [comment]
Haven't been able to reproduce it.... So I'll close this up, and if it happens again I'll pay more attention to it.

**Comment by brandonlehmann** [comment]
You might want to head over to https://blog.turtlecoin.lol/archives/transaction-inputs-and-fusion-transactions-or-what-is-the-max-amount-of-trtl-i-can-send/ with a cup of coffee :)
