### ISSUE TITLE
Version of boost dependency not correct in cmake files.

### ISSUE THREAD

**Issue by arbourp** [CalexCore/AmityCoin-DO-NOT-USE#18]
Found that at least version 1.65.1 of boost is needed to build.
cmake files need to be updated with correct dependency version.

**Comment by michael-herwig** [comment]
Hi! :)

Could you share more insights where the version is required? Further, if so, wee need to update build instructions as well.

**Comment by arbourp** [comment]
The cmake file points to 1.54 and I found that the code won't compile.  I worked my way up a couple versions and eventually gave up and just went to 1.65.1
So know for certain that 1.54 doesn't work and 1.65.1 most definitely does.


The file cmake/Dependencies.cmake
states  Boost 1.54.0 REQUIRED

Needs to be updated to 1.65.1

**Comment by michael-herwig** [comment]
ok^^

- [x] Update Build Instructions
- [x] Update CMake Required Boost Version
