### ISSUE TITLE
Instructions for building on CentOs 7

### ISSUE THREAD

**Issue by arbourp** [CalexCore/AmityCoin-DO-NOT-USE#19]
CentOs:

Installing Correct Version of Cmake
	sudo yum remove cmake -y
	wget https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
	wget https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz
	tar -zxvf cmake-3.6.2.tar.gz
	cd cmake-3.6.2
	sudo ./bootstrap --prefix=/usr/local
	sudo make install
	vi ~/.bash_profile
	PATH=/usr/local/bin:$PATH:$HOME/bin
	cmake --version
	cmake version 3.6.2

Installing newer version of GCC
	sudo yum install centos-release-scl
	sudo yum install devtoolset-7-gcc*
	scl enable devtoolset-7 bash

Installing Boost

yum install python-devel
yum install bzip2-devel
yum install zlib-devel

wget https://cfhcable.dl.sourceforge.net/project/boost/boost/1.65.1/boost_1_65_1.tar.gz
tar -xzf boost_1_65_1.tar.gz
cd boost_1_65_1

./bootstrap.sh --prefix=/opt/boost
./b2 --prefix=/usr --with=all
./b2 install --prefix=/usr --with=all

mkdir build
cd build

cmake ..
make

**Comment by michael-herwig** [comment]
Thanks for your contribution.  The last two steps:
```bash
mkdir build
cd build

cmake ..
make
```
is for building the project itself? Then i would add:
#### GIT
```bash
yum install git
```
#### Downloading AmityCoin
```bash
git cone -b master --single-branch https://github.com/CalexCore/AmityCoin.git
```

#### Building AmityCoin
```bash
mkdir -p AmityCoin/.build
cd AmityCoin/.build
cmake ..
make
# Optional make -j <number_of_threads>
```
#### Installing AmintyCoin
```
DESTDIR="/usr/local/bin" make install
```

**Comment by arbourp** [comment]
Sure, seems good to me. Since all of this lives on the Wiki, I can't really do much but nod 🥇

**Comment by michael-herwig** [comment]
I merged your building instuctions and referenced you within the thanks section. Thank you very much for your contribution. I may checkout CentOS myself :).
