### ISSUE TITLE
Compiling Messages Note

### ISSUE THREAD

**Issue by MaddestHatter** [CalexCore/AmityCoin-DO-NOT-USE#22]
Bereich Zedwallet
[ 83%] Building CXX object src/CMakeFiles/Wallet.dir/WalletLegacy/WalletTransactionSender.cpp.o
In function 'T CryptoNote::{anonymous}::popRandomValue(URNG&, std::vector<T>&) [with URNG = std::linear_congruential_engine<long unsigned int, 16807, 0, 2147483647>; T = long unsigned int]':
cc1plus: warning: 'void* __builtin_memset(void*, int, long unsigned int)': specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]

Bereich BlockchainExplorer
Scanning dependencies of target BlockchainExplorer
[ 92%] Building CXX object src/CMakeFiles/BlockchainExplorer.dir/BlockchainExplorer/BlockchainExplorer.cpp.o
/root/AMIT/amity_bss/AmityCoin/src/BlockchainExplorer/BlockchainExplorer.cpp: In constructor 'CryptoNote::BlockchainExplorer::BlockchainExplorer(CryptoNote::INode&, Logging::ILogger&)':
/root/AMIT/amity_bss/AmityCoin/src/BlockchainExplorer/BlockchainExplorer.cpp:149:1: warning: 'CryptoNote::BlockchainExplorer::database' is initialized with itself [-Winit-self]
 BlockchainExplorer::BlockchainExplorer(INode& node, Logging::ILogger& logger) :
 ^~~~~~~~~~~~~~~~~~

**Comment by michael-herwig** [comment]
Hi Maddest and thanks for your contribution.

Could you provide some detail about you machine setup, please? Ie. compiler version, os system.

**Comment by MaddestHatter** [comment]
photonOS , with docker , docker container ubuntu:latest , GCC GNU 7.3.0 , 
Messages belong to xyz test. 
so maybe unimportent and confusing,  only put it in here , like you told me..
ticket can or should be deleted ? 
Compiling finishes at the end at 100 % . 
ty @michael-herwig

**Comment by michael-herwig** [comment]
Its fine with time going on we should have everything compiling without warnings and setting flags such that every warning is handled as an error.
