### ISSUE TITLE
[RPC] SSL Support

### ISSUE THREAD

**Issue by michael-herwig** [CalexCore/AmityCoin-DO-NOT-USE#26]
Currently the RPC server does not support any ssl encryption, thus everyone willing to use it seriously need to hide all their RPC using connections behind a proxy. We should implement basic HTTPS encryption. Especially since the WalletService sends private keys over.

**Comment by hooftly** [comment]
This makes a lot of sense.  Do you have an idea of how we should implement this in your head?

**Comment by michael-herwig** [comment]
Y, we need openssl and a certificate container. Then everyone can accept encryption signed by their trusted authoroties. Further we could setup an certificate on our own and sign some peoples keys if we think we can trust them.

we may could consider using a [boost](https://www.boost.org/doc/libs/1_50_0/doc/html/boost_asio/example/ssl/client.cpp) http server implementation. this may also fixes #25 and would be more safe since custom implementations like from bytecoin tempt to outdate.
