### ISSUE TITLE
Build failure on Raspbian

### ISSUE THREAD

**Issue by pavulon18** [CalexCore/AmityCoin-DO-NOT-USE#9]
I just tried to build AmityCoin on a RaspberryPi 3 running Raspbian.

This was the output:
`jim@gcems:~/amitycoin/AmityCoin/build $ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:40 (message):
  Targeting a 32-bit architecture is not supported.

-- Configuring incomplete, errors occurred!
See also "/home/jim/amitycoin/AmityCoin/build/CMakeFiles/CMakeOutput.log".
See also "/home/jim/amitycoin/AmityCoin/build/CMakeFiles/CMakeError.log".`

I'll be happy to supply these two log files, if you need them.

**Comment by jerme404** [comment]
Comment out lines 39-41 in CMakeLists.txt

**Comment by brandonlehmann** [comment]
@jerme404 He's likely to encounter numerous segfaults as 32-bit is not *technically* supported.

#### Raspberry Pi 3 (B+)
The following images are known to work. Your operation system image **MUST** be 64 bit with a 64-bit userland space.

##### Known working images

- https://github.com/Crazyhead90/pi64/releases
- https://fedoraproject.org/wiki/Architectures/ARM/Raspberry_Pi#aarch64_supported_images_for_Raspberry_Pi_3
- https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3

Once you have a 64 bit image installed, setup proceeds the same as any Linux distribution. Ensure you have at least 2GB of ram, or the build is likely to fail. You may need to setup swap space.

**Comment by jerme404** [comment]
I missed the part about raspbian not being 64 bit image.  I did still have to comment out the check for arm64 ubuntu.

**Comment by brandonlehmann** [comment]
The cross compile tool chains are funky. Check upstream for cross compiling on x86_64 targeting arm64

**Comment by pavulon18** [comment]
As you suspected, it failed on the RPi.  If you need access to a RPi for testing, I can help you out.

**Comment by CRTNFACE** [comment]
Cheers dude! Im gunna close this but once we start work on making the Pi's work I'll reopen it :+1:
